name: Build and Deploy Unlimited Analytics Landing Page

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write 
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build site
        run: npm run build
      
      - name: Remove symlinks in dist
        run: find dist -type l -exec rm -f {} \;

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist

      - name: Deploy site
        uses: actions/deploy-pages@v4
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: landing-page
          FOLDER: dist
